import { IActivities } from "../interfaces/IActivities";

export const rows: IActivities[] = [
    {
      id: 1,
      timeSchedule: "string",
      subject: "string",
      nrc: 1,
      teacherName: "string",
      classroom: "string",
      input: false,
      timeInput: "string",
      output: false,
      timeOutput: "string",
      classTopic: "string",
      observation: "string",
    },
    {
      id: 1,
      timeSchedule: "string",
      subject: "string",
      nrc: 1,
      teacherName: "string",
      classroom: "string",
      input: false,
      timeInput: "string",
      output: false,
      timeOutput: "string",
      classTopic: "string",
      observation: "string",
    },
    {
      id: 1,
      timeSchedule: "string",
      subject: "string",
      nrc: 1,
      teacherName: "string",
      classroom: "string",
      input: false,
      timeInput: "string",
      output: false,
      timeOutput: "string",
      classTopic: "string",
      observation: "string",
    },{
        id: 1,
        timeSchedule: "string",
        subject: "string",
        nrc: 1,
        teacherName: "string",
        classroom: "string",
        input: false,
        timeInput: "string",
        output: false,
        timeOutput: "string",
        classTopic: "string",
        observation: "string",
      },
      {
        id: 1,
        timeSchedule: "string",
        subject: "string",
        nrc: 1,
        teacherName: "string",
        classroom: "string",
        input: false,
        timeInput: "string",
        output: false,
        timeOutput: "string",
        classTopic: "string",
        observation: "string",
      },
      {
        id: 1,
        timeSchedule: "string",
        subject: "string",
        nrc: 1,
        teacherName: "string",
        classroom: "string",
        input: false,
        timeInput: "string",
        output: false,
        timeOutput: "string",
        classTopic: "string",
        observation: "string",
      },
      {
        id: 1,
        timeSchedule: "string",
        subject: "string",
        nrc: 1,
        teacherName: "string",
        classroom: "string",
        input: false,
        timeInput: "string",
        output: false,
        timeOutput: "string",
        classTopic: "string",
        observation: "string",
      },
      {
        id: 1,
        timeSchedule: "string",
        subject: "string",
        nrc: 1,
        teacherName: "string",
        classroom: "string",
        input: false,
        timeInput: "string",
        output: false,
        timeOutput: "string",
        classTopic: "string",
        observation: "string",
      },
      {
        id: 1,
        timeSchedule: "string",
        subject: "string",
        nrc: 1,
        teacherName: "string",
        classroom: "string",
        input: false,
        timeInput: "string",
        output: false,
        timeOutput: "string",
        classTopic: "string",
        observation: "string",
      },{
        id: 1,
        timeSchedule: "string",
        subject: "string",
        nrc: 1,
        teacherName: "string",
        classroom: "string",
        input: false,
        timeInput: "string",
        output: false,
        timeOutput: "string",
        classTopic: "string",
        observation: "string",
      },
      {
        id: 1,
        timeSchedule: "string",
        subject: "string",
        nrc: 1,
        teacherName: "string",
        classroom: "string",
        input: false,
        timeInput: "string",
        output: false,
        timeOutput: "string",
        classTopic: "string",
        observation: "string",
      },
      {
        id: 1,
        timeSchedule: "string",
        subject: "string",
        nrc: 1,
        teacherName: "string",
        classroom: "string",
        input: false,
        timeInput: "string",
        output: false,
        timeOutput: "string",
        classTopic: "string",
        observation: "string",
      },
  ];